FROM openjdk:17

ARG MYSQL_PORT
ARG MYSQL_HOST
ARG MYSQL_USER
ARG MYSQL_PASSWORD

ENV MYSQL_PORT=$MYSQL_POR
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD

EXPOSE 8085
ADD target/project_tracker-0.0.1-SNAPSHOT.jar  project_tracker-0.0.1-SNAPSHOT.jar 
ENTRYPOINT ["java","-jar","/project_tracker-0.0.1-SNAPSHOT.jar"]
