version: '3'

networks:
  mysql-most:  # Define the custom network

services:
  frontend:
    build: .  # Build the frontend image from the current directory
    ports:
      - "8085:8085"  # Map container port 8085 to host port 8085
    environment:
      - MYSQL_HOST=mysqldb  # Use the service name of the database container
      - MYSQL_PORT=3306  # Standard MySQL port
      - $(cat .env)  # Read environment variables from .env file
    networks:
      - mysql-most  # Connect the frontend to the custom network
    

  db:
    build: ./src  # Build the database image from the directory named 'db'
    environment:
     - MYSQL_ROOT_PASSWORD= root@123
     - MYSQL_HOST= mysqldb
     - MYSQL_DATABASE= bugtracker   
    ports:
     - 3306:3306
    networks:
     - mysql-most  # Connect the database to the custom network

