---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: webapps
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 17rj/bugtracker-fullstack-frontend:v3
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: webapps
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
